version: "3.7"
services:
  app:
    image: harshit30/raghvendra:v2
    container_name: raghvend_rp
    ports:
      - 8800:4435
    volumes:
      - ./.env:/app/.env
    depends_on:
      - postgres
      - redis
    
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: placement_portal
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - data:/var/lib/postgresql
    
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6370:6379

volumes:
  data:
    
